### ISSUE TITLE
Creación de Base de datos

### ISSUE THREAD

**Issue by AugustoMorante** [AugustoMorante/ProyectoTBAlgoritmos#8]
Creación de la Estructura de Base de datos

**Comment by jsroma-2002** [comment]
Clase Base de Datos
class BaseDatos
{
	ifstream archivo;
	string fila;
	vector<vector<string>> bd;

public:

	void lectura(string nombre) {

		archivo.open(nombre);
		while (getline(archivo, fila))
		{
			stringstream ss(fila);
			dividirColumnas(ss);
		}

	}

private:

	void dividirColumnas(istream& ss) {

		vector<string> vCol;
		string campo;

		while (getline(ss, campo, ';'))
		{
			vCol.push_back(campo);
		}
		bd.push_back(vCol);
	}

public:

	void mostrar() {

		for (size_t f = 0; f < bd.size(); f++)
		{
			for (size_t c = 0; c < bd[f].size(); c++)
			{
				cout.width(17); cout << bd[f].at(c);
			}
			cout << endl;
		}

	}

	void dimensiones() {

		cout << "Contidad de cantidad de filas " << bd.size() << endl;
		cout << "Cantidad de columnas " << bd[0].size() << endl;
	}

	int getNumFilas() {

		return bd.size();
	}

	int getNumColumnas(int i) {

		return bd[i].size();
	}

	string getDato(int f, int c) {

		string resultado;
		
		resultado = bd.at(f).at(c);
		
		return resultado;
	}

};
